// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: assignment/assignment.proto

package assignment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignmentStatus int32

const (
	AssignmentStatus_ACTIVE   AssignmentStatus = 0
	AssignmentStatus_RETURNED AssignmentStatus = 1
	AssignmentStatus_OVERDUE  AssignmentStatus = 2
	AssignmentStatus_LOST     AssignmentStatus = 3
)

// Enum value maps for AssignmentStatus.
var (
	AssignmentStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "RETURNED",
		2: "OVERDUE",
		3: "LOST",
	}
	AssignmentStatus_value = map[string]int32{
		"ACTIVE":   0,
		"RETURNED": 1,
		"OVERDUE":  2,
		"LOST":     3,
	}
)

func (x AssignmentStatus) Enum() *AssignmentStatus {
	p := new(AssignmentStatus)
	*p = x
	return p
}

func (x AssignmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assignment_assignment_proto_enumTypes[0].Descriptor()
}

func (AssignmentStatus) Type() protoreflect.EnumType {
	return &file_assignment_assignment_proto_enumTypes[0]
}

func (x AssignmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignmentStatus.Descriptor instead.
func (AssignmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{0}
}

type Assignment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId            string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssignedBy         string                 `protobuf:"bytes,4,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	AssignedDate       string                 `protobuf:"bytes,5,opt,name=assigned_date,json=assignedDate,proto3" json:"assigned_date,omitempty"`
	ExpectedReturnDate string                 `protobuf:"bytes,6,opt,name=expected_return_date,json=expectedReturnDate,proto3" json:"expected_return_date,omitempty"`
	ActualReturnDate   string                 `protobuf:"bytes,7,opt,name=actual_return_date,json=actualReturnDate,proto3" json:"actual_return_date,omitempty"`
	Status             AssignmentStatus       `protobuf:"varint,8,opt,name=status,proto3,enum=assignment.AssignmentStatus" json:"status,omitempty"`
	Notes              string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_assignment_assignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *Assignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assignment) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Assignment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Assignment) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *Assignment) GetAssignedDate() string {
	if x != nil {
		return x.AssignedDate
	}
	return ""
}

func (x *Assignment) GetExpectedReturnDate() string {
	if x != nil {
		return x.ExpectedReturnDate
	}
	return ""
}

func (x *Assignment) GetActualReturnDate() string {
	if x != nil {
		return x.ActualReturnDate
	}
	return ""
}

func (x *Assignment) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ACTIVE
}

func (x *Assignment) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Assignment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Assignment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AssignAssetRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssetId            string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssignedBy         string                 `protobuf:"bytes,3,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	ExpectedReturnDate string                 `protobuf:"bytes,4,opt,name=expected_return_date,json=expectedReturnDate,proto3" json:"expected_return_date,omitempty"`
	Notes              string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssignAssetRequest) Reset() {
	*x = AssignAssetRequest{}
	mi := &file_assignment_assignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssetRequest) ProtoMessage() {}

func (x *AssignAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssetRequest.ProtoReflect.Descriptor instead.
func (*AssignAssetRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *AssignAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssignAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignAssetRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *AssignAssetRequest) GetExpectedReturnDate() string {
	if x != nil {
		return x.ExpectedReturnDate
	}
	return ""
}

func (x *AssignAssetRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AssignAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAssetResponse) Reset() {
	*x = AssignAssetResponse{}
	mi := &file_assignment_assignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssetResponse) ProtoMessage() {}

func (x *AssignAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssetResponse.ProtoReflect.Descriptor instead.
func (*AssignAssetResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *AssignAssetResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type UnassignAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	ReturnedBy    string                 `protobuf:"bytes,2,opt,name=returned_by,json=returnedBy,proto3" json:"returned_by,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignAssetRequest) Reset() {
	*x = UnassignAssetRequest{}
	mi := &file_assignment_assignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignAssetRequest) ProtoMessage() {}

func (x *UnassignAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignAssetRequest.ProtoReflect.Descriptor instead.
func (*UnassignAssetRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{3}
}

func (x *UnassignAssetRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *UnassignAssetRequest) GetReturnedBy() string {
	if x != nil {
		return x.ReturnedBy
	}
	return ""
}

func (x *UnassignAssetRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UnassignAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignAssetResponse) Reset() {
	*x = UnassignAssetResponse{}
	mi := &file_assignment_assignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignAssetResponse) ProtoMessage() {}

func (x *UnassignAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignAssetResponse.ProtoReflect.Descriptor instead.
func (*UnassignAssetResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{4}
}

func (x *UnassignAssetResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_assignment_assignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentResponse) Reset() {
	*x = GetAssignmentResponse{}
	mi := &file_assignment_assignment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentResponse) ProtoMessage() {}

func (x *GetAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GetAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssignmentResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type ListAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        AssignmentStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=assignment.AssignmentStatus" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsRequest) Reset() {
	*x = ListAssignmentsRequest{}
	mi := &file_assignment_assignment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsRequest) ProtoMessage() {}

func (x *ListAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{7}
}

func (x *ListAssignmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssignmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssignmentsRequest) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ACTIVE
}

func (x *ListAssignmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAssignmentsRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ListAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*Assignment          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsResponse) Reset() {
	*x = ListAssignmentsResponse{}
	mi := &file_assignment_assignment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsResponse) ProtoMessage() {}

func (x *ListAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{8}
}

func (x *ListAssignmentsResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ListAssignmentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssignmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssignmentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUserAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        AssignmentStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=assignment.AssignmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssignmentsRequest) Reset() {
	*x = GetUserAssignmentsRequest{}
	mi := &file_assignment_assignment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssignmentsRequest) ProtoMessage() {}

func (x *GetUserAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserAssignmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAssignmentsRequest) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ACTIVE
}

type GetUserAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*Assignment          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssignmentsResponse) Reset() {
	*x = GetUserAssignmentsResponse{}
	mi := &file_assignment_assignment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssignmentsResponse) ProtoMessage() {}

func (x *GetUserAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserAssignmentsResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

var File_assignment_assignment_proto protoreflect.FileDescriptor

const file_assignment_assignment_proto_rawDesc = "" +
	"\n" +
	"\x1bassignment/assignment.proto\x12\n" +
	"assignment\"\x80\x03\n" +
	"\n" +
	"Assignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vassigned_by\x18\x04 \x01(\tR\n" +
	"assignedBy\x12#\n" +
	"\rassigned_date\x18\x05 \x01(\tR\fassignedDate\x120\n" +
	"\x14expected_return_date\x18\x06 \x01(\tR\x12expectedReturnDate\x12,\n" +
	"\x12actual_return_date\x18\a \x01(\tR\x10actualReturnDate\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.assignment.AssignmentStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xb1\x01\n" +
	"\x12AssignAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vassigned_by\x18\x03 \x01(\tR\n" +
	"assignedBy\x120\n" +
	"\x14expected_return_date\x18\x04 \x01(\tR\x12expectedReturnDate\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"M\n" +
	"\x13AssignAssetResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\"r\n" +
	"\x14UnassignAssetRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1f\n" +
	"\vreturned_by\x18\x02 \x01(\tR\n" +
	"returnedBy\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"O\n" +
	"\x15UnassignAssetResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\"&\n" +
	"\x14GetAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetAssignmentResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\"\xb3\x01\n" +
	"\x16ListAssignmentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.assignment.AssignmentStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x05 \x01(\tR\aassetId\"\x9a\x01\n" +
	"\x17ListAssignmentsResponse\x128\n" +
	"\vassignments\x18\x01 \x03(\v2\x16.assignment.AssignmentR\vassignments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"j\n" +
	"\x19GetUserAssignmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.assignment.AssignmentStatusR\x06status\"V\n" +
	"\x1aGetUserAssignmentsResponse\x128\n" +
	"\vassignments\x18\x01 \x03(\v2\x16.assignment.AssignmentR\vassignments*C\n" +
	"\x10AssignmentStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\f\n" +
	"\bRETURNED\x10\x01\x12\v\n" +
	"\aOVERDUE\x10\x02\x12\b\n" +
	"\x04LOST\x10\x032\xd0\x03\n" +
	"\x11AssignmentService\x12N\n" +
	"\vAssignAsset\x12\x1e.assignment.AssignAssetRequest\x1a\x1f.assignment.AssignAssetResponse\x12T\n" +
	"\rUnassignAsset\x12 .assignment.UnassignAssetRequest\x1a!.assignment.UnassignAssetResponse\x12T\n" +
	"\rGetAssignment\x12 .assignment.GetAssignmentRequest\x1a!.assignment.GetAssignmentResponse\x12Z\n" +
	"\x0fListAssignments\x12\".assignment.ListAssignmentsRequest\x1a#.assignment.ListAssignmentsResponse\x12c\n" +
	"\x12GetUserAssignments\x12%.assignment.GetUserAssignmentsRequest\x1a&.assignment.GetUserAssignmentsResponseB*Z(internal-support-system/proto/assignmentb\x06proto3"

var (
	file_assignment_assignment_proto_rawDescOnce sync.Once
	file_assignment_assignment_proto_rawDescData []byte
)

func file_assignment_assignment_proto_rawDescGZIP() []byte {
	file_assignment_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_assignment_proto_rawDesc), len(file_assignment_assignment_proto_rawDesc)))
	})
	return file_assignment_assignment_proto_rawDescData
}

var file_assignment_assignment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assignment_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_assignment_assignment_proto_goTypes = []any{
	(AssignmentStatus)(0),              // 0: assignment.AssignmentStatus
	(*Assignment)(nil),                 // 1: assignment.Assignment
	(*AssignAssetRequest)(nil),         // 2: assignment.AssignAssetRequest
	(*AssignAssetResponse)(nil),        // 3: assignment.AssignAssetResponse
	(*UnassignAssetRequest)(nil),       // 4: assignment.UnassignAssetRequest
	(*UnassignAssetResponse)(nil),      // 5: assignment.UnassignAssetResponse
	(*GetAssignmentRequest)(nil),       // 6: assignment.GetAssignmentRequest
	(*GetAssignmentResponse)(nil),      // 7: assignment.GetAssignmentResponse
	(*ListAssignmentsRequest)(nil),     // 8: assignment.ListAssignmentsRequest
	(*ListAssignmentsResponse)(nil),    // 9: assignment.ListAssignmentsResponse
	(*GetUserAssignmentsRequest)(nil),  // 10: assignment.GetUserAssignmentsRequest
	(*GetUserAssignmentsResponse)(nil), // 11: assignment.GetUserAssignmentsResponse
}
var file_assignment_assignment_proto_depIdxs = []int32{
	0,  // 0: assignment.Assignment.status:type_name -> assignment.AssignmentStatus
	1,  // 1: assignment.AssignAssetResponse.assignment:type_name -> assignment.Assignment
	1,  // 2: assignment.UnassignAssetResponse.assignment:type_name -> assignment.Assignment
	1,  // 3: assignment.GetAssignmentResponse.assignment:type_name -> assignment.Assignment
	0,  // 4: assignment.ListAssignmentsRequest.status:type_name -> assignment.AssignmentStatus
	1,  // 5: assignment.ListAssignmentsResponse.assignments:type_name -> assignment.Assignment
	0,  // 6: assignment.GetUserAssignmentsRequest.status:type_name -> assignment.AssignmentStatus
	1,  // 7: assignment.GetUserAssignmentsResponse.assignments:type_name -> assignment.Assignment
	2,  // 8: assignment.AssignmentService.AssignAsset:input_type -> assignment.AssignAssetRequest
	4,  // 9: assignment.AssignmentService.UnassignAsset:input_type -> assignment.UnassignAssetRequest
	6,  // 10: assignment.AssignmentService.GetAssignment:input_type -> assignment.GetAssignmentRequest
	8,  // 11: assignment.AssignmentService.ListAssignments:input_type -> assignment.ListAssignmentsRequest
	10, // 12: assignment.AssignmentService.GetUserAssignments:input_type -> assignment.GetUserAssignmentsRequest
	3,  // 13: assignment.AssignmentService.AssignAsset:output_type -> assignment.AssignAssetResponse
	5,  // 14: assignment.AssignmentService.UnassignAsset:output_type -> assignment.UnassignAssetResponse
	7,  // 15: assignment.AssignmentService.GetAssignment:output_type -> assignment.GetAssignmentResponse
	9,  // 16: assignment.AssignmentService.ListAssignments:output_type -> assignment.ListAssignmentsResponse
	11, // 17: assignment.AssignmentService.GetUserAssignments:output_type -> assignment.GetUserAssignmentsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_assignment_assignment_proto_init() }
func file_assignment_assignment_proto_init() {
	if File_assignment_assignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_assignment_proto_rawDesc), len(file_assignment_assignment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_assignment_proto_depIdxs,
		EnumInfos:         file_assignment_assignment_proto_enumTypes,
		MessageInfos:      file_assignment_assignment_proto_msgTypes,
	}.Build()
	File_assignment_assignment_proto = out.File
	file_assignment_assignment_proto_goTypes = nil
	file_assignment_assignment_proto_depIdxs = nil
}
